//  for signin
export const AUTH_WATCHER = 'AUTH_WATCHER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const RESET_AUTH_STATUS = 'RESET_AUTH_STATUS';

//  for signin
export const SIGNUP_WATCHER = 'SIGNUP_WATCHER';

//  for logout
export const LOG_OUT_WATCHER = 'LOG_OUT_WATCHER';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

//  for currency
export const SET_CURRENCY = 'SET_CURRENCY';

//  for cart list 
export const GET_CART_LIST_WATCHER = 'GET_CART_LIST_WATCHER';
export const GET_CART_LIST_SUCCESS = 'GET_CART_LIST_SUCCESS';
export const GET_CART_LIST_FAILURE = 'GET_CART_LIST_FAILURE';
export const RESET_GET_CART_LIST_STATUS = 'RESET_GET_CART_LIST_STATUS';

//  for add to cart 
export const SAVE_TO_CART_WATCHER = 'SAVE_TO_CART_WATCHER';
export const SAVE_TO_CART_SUCCESS = 'SAVE_TO_CART_SUCCESS';
export const SAVE_TO_CART_FAILURE = 'SAVE_TO_CART_FAILURE';
export const RESET_SAVE_TO_CART_STATUS = 'RESET_SAVE_TO_CART_STATUS';

//  for add to cart 
export const UPDATE_CART_WATCHER = 'UPDATE_WATCHER';
export const UPDATE_CART_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_FAILURE';
export const RESET_UPDATE_CART_STATUS = 'RESET_UPDATE_STATUS';

//  for remove from cart
export const REMOVE_FROM_CART_WATCHER = 'REMOVE_FROM_CART_WATCHER';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';
export const RESET_REMOVE_FROM_CART_STATUS = 'RESET_REMOVE_FROM_CART_STATUS';

//  for get pizza list
export const GET_PIZZA_LIST_WATCHER = 'GET_PIZZA_LIST_WATCHER';
export const GET_PIZZA_LIST_SUCCESS = 'GET_PIZZA_LIST_SUCCESS';
export const GET_PIZZA_LIST_FAILURE = 'GET_PIZZA_LIST_FAILURE';
export const RESET_GET_PIZZA_LIST_STATUS = 'RESET_GET_PIZZA_LIST_STATUS';

//  for place order
export const SAVE_ORDER_WATCHER = 'SAVE_ORDER_WATCHER';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE';
export const RESET_SAVE_ORDER_STATUS = 'RESET_SAVE_ORDER_STATUS';

//  for order list
export const GET_ORDER_LIST_WATCHER = 'GET_ORDER_LIST_WATCHER';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILURE = 'GET_ORDER_LIST_FAILURE';
export const RESET_GET_ORDER_LIST_STATUS = 'RESET_GET_ORDER_LIST_STATUS';

//  for loader
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';